services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # Map container's port 5000 to localhost:5000
    volumes:
      - ./app:/app  # Mounts the app folder for easier development
